<a href="https://colab.research.google.com/github/Omid-Hassasfar/CHACAL_2024_Quantum_Computing_Basics_with_Qiskit/blob/main/26_June_2024_MicroSchool_NITheCS_Abbas(Omid)_Hassasfar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NITheCS Micro school on Numpy!
June 26, 2024
Abbas(Omid) Hassasfar

Download Notebook: https://github.com/Omid-Hassasfar/MicroSchool_NITheCS_2024

You can reach me out here: https://linktr.ee/hassasfar

## Check the pre-installed packages and their versions on Google Colab.

In [ ]:
# Check the python version

!python --version

Python 3.10.12


In [ ]:
# List installed Python packages

!pip list

Package                          Version
-------------------------------- ---------------------
absl-py                          1.4.0
aiohttp                          3.9.5
aiosignal                        1.3.1
alabaster                        0.7.16
albumentations                   1.3.1
altair                           4.2.2
annotated-types                  0.7.0
anyio                            3.7.1
argon2-cffi                      23.1.0
argon2-cffi-bindings             21.2.0
array_record                     0.5.1
arviz                            0.15.1
astropy                          5.3.4
astunparse                       1.6.3
async-timeout                    4.0.3
atpublic                         4.1.0
attrs                            23.2.0
audioread                        3.0.1
autograd                         1.6.2
Babel                            2.15.0
backcall                         0.2.0
beautifulsoup4                   4.12.3
bidict                           0.23.1

---
---
## Python Data Types: https://www.w3schools.com/python/python_datatypes.asp

NumPy Package : The fundamental package for scientific computing with Python: https://numpy.org/


---
---
Why Numpy is useful:

Memory-efficient container that provides fast numerical operations.
Working with lists would quickly become very complicated if we wanted to do numerical operations on many elements at the same time, or if, for example, we want to be able to construct vectors and matrices in our programs. All of these features, and more, come with using NumPy arrays as our preferred data structure.

In [ ]:
# Importing the libraries

import numpy as np
import time

In [ ]:
print(np.__version__)

1.25.2


### List vs NumPy Array.

In [ ]:
L1 = [-3, -2, 0, -1, 4]
print(L1)

[-3, -2, 0, -1, 4]


In [ ]:
L2 = [-1, -1, 2, -3, 5]
L2

[-1, -1, 2, -3, 5]

In [ ]:
type(L1), type(L1), len(L2), len(L2)

(list, list, 5, 5)

Let's add them together!

In [ ]:
# Be careful! In this case, the + operator concatenates the two lists instead of performing element-wise addition.

L3 = L1 + L2
L3

[-3, -2, 0, -1, 4, -1, -1, 2, -3, 5]

In [ ]:
type(L3), len(L3)

(list, 10)

In [ ]:
L4 = L3 * 2
L4

[-3, -2, 0, -1, 4, -1, -1, 2, -3, 5, -3, -2, 0, -1, 4, -1, -1, 2, -3, 5]

In [ ]:
len(L4)

20

In [ ]:
L1 + 1

TypeError: can only concatenate list (not "int") to list

Let's perform element-wise addition using Python lists!

In [ ]:
result1 = []

for i in range(len(L1)):
    result1.append(L1[i]+L2[i])

print(" (L1 + L2) is", result1)

 (L1 + L2) is [-4, -3, 2, -4, 9]


In [ ]:
type(result1), len(result1)

(list, 5)

In [ ]:
# Another method of element-wise addition

result_list = [a + b for a, b in zip(L1, L2)]
result_list

[-4, -3, 2, -4, 9]

---
---
Let's do it with NumPy Array

In [ ]:
A1 = np.array([-3,-2,0,-1,4])
A1

array([-3, -2,  0, -1,  4])

In [ ]:
type(A1) , len(A1), A1.shape, A1.ndim

(numpy.ndarray, 5, (5,), 1)

In [ ]:
A1 + 2

array([-1,  0,  2,  1,  6])

In [ ]:
A1 * 3 # element-wise

array([-9, -6,  0, -3, 12])

In [ ]:
A2 = np.array([-1,-1,2,-3,5])
A2

array([-1, -1,  2, -3,  5])

In [ ]:
type(A2) , len(A2), A2.shape, A2.ndim

(numpy.ndarray, 5, (5,), 1)

In [ ]:
print(A1 + A2)   # In this case, the + operator performs element-wise addition on the two NumPy arrays.
type(A1 + A2), len(A1 + A2)

[-4 -3  2 -4  9]


(numpy.ndarray, 5)

---
---

Data types in Python list and Numpy!


In [ ]:
# Python list with heterogeneous data types
list_mixed = [1, "hello", 3.14, True]

print("Python list with mixed types:", list_mixed)

# In this case, the list contains an integer, a string, a float, and a boolean.

Python list with mixed types: [1, 'hello', 3.14, True]


In [ ]:
type(list_mixed[1])

str

In [ ]:
type(list_mixed[3])

bool

NumPy arrays are designed to hold elements of a single data type. When creating an array with mixed types, NumPy will attempt to convert all elements to a common type, usually the most general one (e.g., strings).

In [ ]:
# NumPy array with mixed types
array_mixed = np.array([1, "hello", 3.14, True])

#In this case, NumPy converts all elements to *strings* because it's the most general type that can represent all the input values

In [ ]:
print("NumPy array with mixed types:", array_mixed)
print("Data type of NumPy array elements:", array_mixed.dtype)

NumPy array with mixed types: ['1' 'hello' '3.14' 'True']
Data type of NumPy array elements: <U32


In [ ]:
array_mixed[3].dtype

dtype('<U4')

<U32: This represents a Unicode string with a maximum length of 32 characters.    
<U4: This represents a Unicode string with a maximum length of 4 characters.

---
---

### Dot product:

In [ ]:
print(A1)
print(A2)

[-3 -2  0 -1  4]
[-1 -1  2 -3  5]


In [ ]:
# A1 @ A2 performs the Dot product of A1 & A2, which is the sum of the products of the corresponding elements in the arrays.
A1 @ A2

28

In [ ]:
np.dot(A1,A2)

28

In [ ]:
L1 @ L2 # for list we can not use @

TypeError: unsupported operand type(s) for @: 'list' and 'list'

Dot product with list!

In [ ]:
print(L1)
print(L2)

[-3, -2, 0, -1, 4]
[-1, -1, 2, -3, 5]


In [ ]:
SUM = 0; # summation is initially zero

for i in range(len(L1)): # iteratively access every pair with the same indices
    SUM = SUM + L1[i]*L2[i] # i-th entries are multiplied and then added to summation
print("The dot product of",L1,'and',L2,'is', SUM)

The dot product of [-3, -2, 0, -1, 4] and [-1, -1, 2, -3, 5] is 28


In [ ]:
#Another method to define dot product with list!

dot_product = sum([a * b for a, b in zip(L1, L2)])
dot_product

28

---
---
## Matrix multiplication with Numpy

In 2D, the first dimension corresponds to rows, the second to columns.

In [ ]:
M1 = np.array([ [4 , 0 , -1 , 0 , 2], [-2 , -3 , 1 , 1 , 4], [0 , 0 , 1 , -7 , 1], [1 , 4 , -2 , 5 , 5]] )
M1

array([[ 4,  0, -1,  0,  2],
       [-2, -3,  1,  1,  4],
       [ 0,  0,  1, -7,  1],
       [ 1,  4, -2,  5,  5]])

In [ ]:
# SymPy Pretty Printing: SymPy provides a function init_printing that initializes pretty printing, making the output look nicer

import sympy as sp
sympy_matrix = sp.Matrix(M1)
sympy_matrix

Matrix([
[ 4,  0, -1,  0, 2],
[-2, -3,  1,  1, 4],
[ 0,  0,  1, -7, 1],
[ 1,  4, -2,  5, 5]])

In [ ]:
type(M1), M1.shape, M1.ndim, M1.size

(numpy.ndarray, (4, 5), 2, 20)

In [ ]:
M2 =  -2*M1
M2

array([[ -8,   0,   2,   0,  -4],
       [  4,   6,  -2,  -2,  -8],
       [  0,   0,  -2,  14,  -2],
       [ -2,  -8,   4, -10, -10]])

In [ ]:
type(M2), M2.shape, M2.ndim, M2.size

(numpy.ndarray, (4, 5), 2, 20)

In [ ]:
np.multiply(M1, M2)  # Returns the element-wise matrix multiplication!

array([[-32,   0,  -2,   0,  -8],
       [ -8, -18,  -2,  -2, -32],
       [  0,   0,  -2, -98,  -2],
       [ -2, -32,  -8, -50, -50]])

Let's perform standard Matrix multiplication!

In [ ]:
M3 = np.array([ [8 , 0 , -1 , 0 ], [-2 , -3 , 1 , 1], [0 , 0 , 1 , -7], [1 , 4 , -2 , 5] ,[8 , -4 , -2 , 0] ] )
M3

array([[ 8,  0, -1,  0],
       [-2, -3,  1,  1],
       [ 0,  0,  1, -7],
       [ 1,  4, -2,  5],
       [ 8, -4, -2,  0]])

In [ ]:
type(M3), M3.shape, M3.ndim, M3.size

(numpy.ndarray, (5, 4), 2, 20)

In [ ]:
M4 = np.matmul(M1, M3)
M4

array([[ 48,  -8,  -9,   7],
       [ 23,  -3, -10,  -5],
       [  1, -32,  13, -42],
       [ 45, -12, -19,  43]])

In [ ]:
type(M4), M4.shape, M4.ndim, M4.size

(numpy.ndarray, (4, 4), 2, 16)

In [ ]:
# Adding 2 Mattices
M1 + M2

array([[-4,  0,  1,  0, -2],
       [ 2,  3, -1, -1, -4],
       [ 0,  0, -1,  7, -1],
       [-1, -4,  2, -5, -5]])

In [ ]:
# Be careful about dimensions

np.matmul(M1, M2)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 5)

Example of Multiplying a Matrix with a Vector using Dot Product

In [ ]:
# Define a matrix
matrix = np.array([[1, 2, 3],
                   [3, 2, 1]])

# Define a vector
vector = np.array([1, 2, 4])

# Compute the dot product (matrix-vector multiplication)
result = np.dot(matrix, vector)

print("Result of matrix-vector multiplication:", result)

Result of matrix-vector multiplication: [17 11]


A small illustrated summary of NumPy indexing and slicing.

In [ ]:
M4 = np.array([ [8 , 110 , -11 , -50 ], [-2 , -3 , 1 , 13], [20 , -30 , -14 , -7], [1 , 4 , -6 , 5] ,[-8 , -4 , 6 , 0] ] )
M4

array([[  8, 110, -11, -50],
       [ -2,  -3,   1,  13],
       [ 20, -30, -14,  -7],
       [  1,   4,  -6,   5],
       [ -8,  -4,   6,   0]])

In [ ]:
M3.size, M3.shape, M3.ndim

(20, (5, 4), 2)

How you can access elements of an array

In [ ]:
M3[0]

array([ 8,  0, -1,  0])

In [ ]:
M3[-1]

array([ 8, -4, -2,  0])

In [ ]:
M3[4]

array([ 8, -4, -2,  0])

In [ ]:
M3[4,2]

-2

In [ ]:
print(M3[:, 2])

[-1  1  1 -2 -2]


### We can go beyond Vector (1D) & Matrix (2D)!   
Let's start by 3D array which is a bunch of 2D (Matrix)!

In [ ]:
M6 = np.array([
    [[0, 1], [2, 3], [4, 5]],

    [[6, 7], [8, 9], [0, 1]],

    [[2, 3], [4, 5], [6, 7]],

    [[8, 9], [0, 1], [2, 3]]
] )

M6  # 4 * (2*3)

array([[[0, 1],
        [2, 3],
        [4, 5]],

       [[6, 7],
        [8, 9],
        [0, 1]],

       [[2, 3],
        [4, 5],
        [6, 7]],

       [[8, 9],
        [0, 1],
        [2, 3]]])

In [ ]:
sp.Matrix(M6)

NotImplementedError: SymPy supports just 1D and 2D matrices

In [ ]:
# Function to convert and display each slice of the 3D matrix
def display_3d_matrix(matrix):
    depth = matrix.shape[0]
    for i in range(depth):
        print(f"Slice {i+1}:")
        sympy_slice = sp.Matrix(matrix[i])
        display(sympy_slice)

In [ ]:
display_3d_matrix(M6)

Slice 1:


Matrix([
[0, 1],
[2, 3],
[4, 5]])

Slice 2:


Matrix([
[6, 7],
[8, 9],
[0, 1]])

Slice 3:


Matrix([
[2, 3],
[4, 5],
[6, 7]])

Slice 4:


Matrix([
[8, 9],
[0, 1],
[2, 3]])

In [ ]:
M6.shape

(4, 3, 2)

In [ ]:
M6.ndim

3

In [ ]:
M6.size

24

In [ ]:
type(M6)

numpy.ndarray

First Dimension (4):
This is the outermost dimension.
It indicates that there are 4 separate 2-dimensional arrays (or "slices").

Second Dimension (3):
Each of the 4 slices has 3 rows.
This dimension specifies the number of rows in each 2-dimensional array.

Third Dimension (2):
Each row in every slice has 2 columns.
This dimension specifies the number of columns in each row.

In [ ]:
M6.shape[0] == len(M6)

True

In [ ]:
M6[0,2,1]

5

In [ ]:
M6[3,1,:]

array([0, 1])

## NumPy Vectorization Vs Python for Loop

In [ ]:
# Generate a large array of random numbers
large_array = np.random.rand(40000000) # 4e7 == 40000000

In [ ]:
large_array.shape

(40000000,)

In [ ]:
large_array[100]

0.7207098385750569

In [ ]:
# Using a Python for loop
start_time = time.time()

squared_array = [x**2 for x in large_array]

end_time = time.time()

print(f"Time taken using Python for loop: {end_time - start_time} seconds")

Time taken using Python for loop: 9.310584783554077 seconds


In [ ]:
squared_array[100]

0.5194226714188845

In [ ]:
# Using NumPy vectorization
start_time = time.time()

squared_array_np = large_array**2

end_time = time.time()

print(f"Time taken using NumPy vectorization: {end_time - start_time} seconds")

Time taken using NumPy vectorization: 0.14204192161560059 seconds


## More on NumPy: different built in functions

In [ ]:
# Creating an array with a range of values   * np.arange*
arange_array = np.arange(13)
print("Array with arange (0 to 9):\n", arange_array)

Array with arange (0 to 9):
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
# Creating an array with a specified start, stop, and step
arange_array_step = np.arange(3, 22, 2)
print("Array with arange (1 to 9 with step 2):\n", arange_array_step)

Array with arange (1 to 9 with step 2):
 [ 3  5  7  9 11 13 15 17 19 21]


In [ ]:
# Creating an array with evenly spaced values
linspace_array = np.linspace(0, 30, 5)
print("Array with linspace (0 to 30 with 5 points):\n", linspace_array)

Array with linspace (0 to 30 with 5 points):
 [ 0.   7.5 15.  22.5 30. ]


In [ ]:
# Creating an identity matrix
identity_matrix = np.identity(5)
print("Identity matrix (5x5):\n", identity_matrix)

Identity matrix (5x5):
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# Creating an eye matrix with diagonal offset
eye_matrix = np.eye(5, k=1)
print("Eye matrix (5x5) with diagonal offset by 1:\n", eye_matrix)

Eye matrix (5x5) with diagonal offset by 1:
 [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# Creating an array of random values between 0 and 1
random_array = np.random.rand(3, 3)
print("Random array (3x3) with values between 0 and 1:\n", random_array)

Random array (3x3) with values between 0 and 1:
 [[0.83064721 0.03046119 0.79747811]
 [0.44644556 0.18195855 0.69246366]
 [0.70760446 0.7813801  0.84462863]]


In [ ]:
# Creating an array of random integers
random_int_array = np.random.randint(1, 20, (3, 3))
print("Random integer array (3x3) with values between 1 and 9:\n", random_int_array)

Random integer array (3x3) with values between 1 and 9:
 [[14 17 17]
 [11 14  3]
 [ 1  5  6]]


In [ ]:
# Creating an array and reshaping it
original_array = np.arange(12)
reshaped_array = original_array.reshape((3, 4))
print("Original array (0 to 11):\n", original_array)
print("Reshaped array (3x4):\n", reshaped_array)

Original array (0 to 11):
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# Creating an array of ones
ones_array = np.ones((3, 5))
print("Array of ones:\n", ones_array)

Array of ones:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# Create a 2x3 matrix filled with the value 7
matrix = np.full((2, 3), 7)

print("2x3 matrix filled with 7:")
print(matrix)

2x3 matrix filled with 7:
[[7 7 7]
 [7 7 7]]


---
---

In [ ]:
A5 = np.arange(30)
A5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
A5[0]

0

In [ ]:
A5[-1]

29

In [ ]:
A5[3:27:3]

array([ 3,  6,  9, 12, 15, 18, 21, 24])

In [ ]:
from IPython.display import Image

Image(url="https://scipy-lectures.org/_images/numpy_indexing.png")

In [ ]:
# fancy indexing applications
Image(url="https://lectures.scientific-python.org/_images/numpy_fancy_indexing.png")

## NumPy Cheat Sheets: https://www.kaggle.com/discussions/getting-started/255139